//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootlegSteam
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev
    {
        public dev()
        {
            this.games = new HashSet<game>();
        }
    
        public long id { get; set; }
        public string title { get; set; }
        public byte[] picture { get; set; }
        public System.DateTime creation { get; set; }
        public string country { get; set; }
        public long popularity { get; set; }
        public long age { get; set; }
    
        public virtual ICollection<game> games { get; set; }
    }
}
