//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootlegSteam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class steamdbEntities : DbContext
    {
        public steamdbEntities()
            : base("name=steamdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dev> devs { get; set; }
        public DbSet<game> games { get; set; }
        public DbSet<genre> genres { get; set; }
        public DbSet<icon> icons { get; set; }
        public DbSet<player> players { get; set; }
        public DbSet<stat> stats { get; set; }
    }
}
