//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootlegSteam
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public player()
        {
            this.devs = new HashSet<dev>();
        }
    
        public long id { get; set; }
        public string title { get; set; }
        public System.DateTime creation { get; set; }
        public long iconid { get; set; }
        public long statid { get; set; }
    
        public virtual ICollection<dev> devs { get; set; }
        public virtual icon icon { get; set; }
        public virtual stat stat { get; set; }
    }
}
