//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootlegSteam
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat
    {
        public stat()
        {
            this.players = new HashSet<player>();
        }
    
        public long id { get; set; }
        public long timespent { get; set; }
        public long perfectgame { get; set; }
        public long acclevel { get; set; }
        public long moneyspent { get; set; }
    
        public virtual ICollection<player> players { get; set; }
    }
}
